FROM ghcr.io/coder/code-server:4.92.2

RUN sudo apt update \
 && sudo apt install -y --no-install-recommends \
  gcc \
  cmake \
  make \
  clang \
  pkg-config \
  gcc-multilib \
  build-essential \
  net-tools \
  musl-tools \
  protobuf-compiler \
  curl \
  netcat-openbsd \
  libffi-dev \
  libgmp-dev \
  libgmp10 \
  libncurses-dev \
  libncurses5 \
  libtinfo5
