apiVersion: v1
kind: ConfigMap
metadata:
  name: namenode-config
data:
  init.sh: |-
    #!/bin/bash
    if [ ! -e "/namenode/current" ]; then
      hdfs namenode -format
    fi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: namenode
  name: namenode
spec:
  ports:
  - name: rpc
    port: 8020
    protocol: TCP
    targetPort: rpc
  - name: http
    port: 9870
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: namenode
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: namenode
  name: namenode
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: default
      app.kubernetes.io/name: namenode
  serviceName: namenode
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: default
        app.kubernetes.io/name: namenode
    spec:
      initContainers:
      - name: format
        image: icymint/hadoop:3.2.2
        imagePullPolicy: Always
        command:
        - /bin/init.sh
        volumeMounts:
        - name: namenode-config
          mountPath: /bin/init.sh
          readOnly: true
          subPath: init.sh
        - name: namenode-dir
          mountPath: /namenode
      containers:
      - name: namenode
        image: icymint/hadoop:3.2.2
        imagePullPolicy: IfNotPresent
        ports:
        - name: rpc
          containerPort: 8020
        - name: http
          containerPort: 9870
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command:
        - hdfs
        - namenode
        volumeMounts:
        - name: namenode-config
          mountPath: /bin/init.sh
          readOnly: true
          subPath: init.sh
        - name: namenode-dir
          mountPath: /namenode
      volumes:
      - name: namenode-config
        configMap:
          defaultMode: 0700
          name: namenode-config
      - name: namenode-dir
        emptyDir: {}