name: Build Docker Image

on:
  push:
    branches-ignore:
    - main
    paths:
      - 'code/**'
      - 'tor/**'
  pull_request:
    branches-ignore:
    - main
    paths:
      - 'code/**'
      - 'tor/**'

jobs:
  changes:
    name: Get changes
    runs-on: ubuntu-latest
    outputs:
      matrix: "{\"container\": ${{ steps.reduce.outputs.containers }} }"
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: json
          base: main
          filters: |
            changed:
            - added|modified:
              - 'code/**'
              - 'tor/**'
      - id: reduce
        run: |
          echo '${{ toJson(steps.filter.outputs) }}' | tee changes.json
          CONTAINERS=$(jq -cM --raw-output '.changed_files | fromjson | .[] |= sub("\/.*";"") | unique' changes.json)
          echo ::set-output name=containers::${CONTAINERS}
  build:
    runs-on: ubuntu-latest
    needs:
      - changes
    strategy:
      matrix: ${{ fromJson(needs.changes.outputs.matrix) }}
      fail-fast: false
    steps:
    - name: Check out the repo
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
    - name: Get Version
      id: get_ver
      run: |
        if [ "${{ matrix.container }}" = "code" ]; then
          RELEASE_VERSION="$(awk -F: '/FROM/{print $2}' ${{ matrix.container }}/Dockerfile)"
        fi
        if [ -z "$RELEASE_VERSION" ]; then
          RELEASE_VERSION=$(date +%Y%m%d)
        fi
        echo $RELEASE_VERSION
        echo ::set-output name=ver::$RELEASE_VERSION
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: icymint
        password: ${{ secrets.DOCKER_PASS }}
    - name: Build and Push
      uses: docker/build-push-action@729f7f49266dec5e72fe7339273d3f7e65abacd7
      with:
        context: ${{ matrix.container }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          icymint/${{matrix.container}}:v${{ steps.get_ver.outputs.ver }}
          icymint/${{matrix.container}}:${{ steps.get_ver.outputs.ver }}
          icymint/${{matrix.container}}:latest
