name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: icymint
        password: ${{ secrets.DOCKER_PASS }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@ee266832e57cb510bc6060ce5129df0529f119df
      with:
        images: icymint/code
    - name: Build and Push
      uses: docker/build-push-action@1527803881d0d3d1073ef4278b1168264ce2f779
      with:
        context: code
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
