name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver: docker
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: icymint
        password: ${{ secrets.DOCKER_PASS }}
    - name: Build and Push
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: icymint/code
        tags: latest, 4.5.1-v2
        directory: code
        registry: docker.io
        dockerfile: code/Dockerfile
